"use client";

import MaterialOverview from "@/components/pages/Root/Drawing/MaterialOverview";
import { getProjectById, updateProject } from "@/lib/network/project";
import { CreateProjectType } from "@/lib/type/project";
import { Excalidraw, MainMenu } from "@excalidraw/excalidraw";
import {
  ExcalidrawElement,
  NonDeleted,
} from "@excalidraw/excalidraw/types/element/types";
import {
  ExcalidrawImperativeAPI,
  LibraryItem,
} from "@excalidraw/excalidraw/types/types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Save } from "lucide-react";
import { useParams } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";

export default function ExcalidrawTest() {
  const params = useParams();
  const projectId = params.projectId as string;

  const queryClient = useQueryClient();
  const [excalidrawAPI, setExcalidrawAPI] =
    useState<ExcalidrawImperativeAPI | null>(null);

  const { data: project } = useQuery({
    queryFn: () => getProjectById(projectId),
    queryKey: ["projects", projectId],
  });

  const drawingData = project?.drawing
    ? JSON.parse(project.drawing)
    : { elements: [], appState: {} };

  const { mutate: onUpdateProject } = useMutation({
    mutationFn: (values: CreateProjectType) => updateProject(projectId, values),
    onSuccess: () => {
      toast.success("Project Saved!");
      queryClient.invalidateQueries({
        queryKey: ["projects", projectId],
      });
    },
    onError: (error) => {
      toast.error("Something went wrong!");
      console.log(error);
    },
  });

  async function handleSave() {
    if (excalidrawAPI) {
      const elements = excalidrawAPI.getSceneElements();
      const appState = excalidrawAPI.getAppState();

      const drawingData = {
        elements,
        appState,
      };

      await onUpdateProject({
        drawing: JSON.stringify(drawingData),
      });
    }
  }
  const initialLibraryItems: LibraryItem[] = [
    {
      id: "tiang-beton",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "tiang-beton",
          type: "ellipse",
          x: 0,
          y: 0,
          width: 125,
          height: 125,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 3,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          roundness: {
            type: 2,
          },
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "tiang-besi",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "tiang-beton",
          type: "ellipse",
          x: 0,
          y: 0,
          width: 125,
          height: 125,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "#1e1e1e",
          fillStyle: "solid",
          strokeWidth: 3,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          roundness: {
            type: 2,
          },
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "grouped-lines",
      status: "published",
      created: Date.now(),
      elements: [
        {
          type: "line",
          version: 77,
          versionNonce: 363115522,
          index: "aJ",
          isDeleted: false,
          id: "wBtWb4cHq6-Z7MU34s_fU",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 587.3733333333333,
          y: 198.64333333333335,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 0,
          height: 72.06666666666668,
          seed: 1581794562,
          groupIds: ["group-1"],
          frameId: null,
          roundness: {
            type: 2,
          },
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [0, 72.06666666666668],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 175,
          versionNonce: 470389534,
          index: "aK",
          isDeleted: false,
          id: "YBdtskrxnE2xo9BMx-yE4",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 588,
          y: 324.28999999999996,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 0,
          height: 72.06666666666668,
          seed: 1824281794,
          groupIds: ["group-1"],
          frameId: null,
          roundness: {
            type: 2,
          },
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [0, 72.06666666666668],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 333,
          versionNonce: 1910865758,
          index: "aL",
          isDeleted: false,
          id: "uYNi_Yy1x8opPYzl1b4nF",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 635,
          y: 277.9166666666667,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 46.373333333333335,
          height: 45.74666666666667,
          seed: 2040032386,
          groupIds: ["group-1"],
          frameId: null,
          roundness: {
            type: 2,
          },
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [-46.373333333333335, 45.74666666666667],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 379,
          versionNonce: 905569182,
          index: "aM",
          isDeleted: false,
          id: "-2LrBhjbkr6S94t6ZPqP-",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 587.3733333333333,
          y: 271.65,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 46.373333333333335,
          height: 45.74666666666667,
          seed: 177966146,
          groupIds: ["group-1"],
          frameId: null,
          roundness: {
            type: 2,
          },
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [-46.373333333333335, 45.74666666666667],
          ],
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "trafo",
      status: "published",
      created: Date.now(),
      elements: [
        {
          type: "rectangle",
          version: 60,
          versionNonce: 1320332674,
          index: "aR",
          isDeleted: false,
          id: "1DnUnmJEzFfRiqfI6Jonz",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 522.5,
          y: 196.5,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 321,
          height: 240,
          seed: 658439810,
          groupIds: ["owj0nAfUZGcqsQuYUUW5J"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 120,
          versionNonce: 758801310,
          index: "aS",
          isDeleted: false,
          id: "98TFLwhH1dCrngvfawayl",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 555.5,
          y: 409.5,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 259,
          height: 0,
          seed: 698342978,
          groupIds: ["owj0nAfUZGcqsQuYUUW5J"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [259, 0],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 282,
          versionNonce: 616934722,
          index: "aT",
          isDeleted: false,
          id: "jpoaj4_2fWwAJ6ubJYMiF",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 556,
          y: 407.5,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 126,
          height: 188,
          seed: 877577730,
          groupIds: ["owj0nAfUZGcqsQuYUUW5J"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [126, -188],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 410,
          versionNonce: 900218846,
          index: "aU",
          isDeleted: false,
          id: "uK1gNXHayl79-YdmaNnwU",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 681.5,
          y: 219.5,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 132,
          height: 189,
          seed: 541767106,
          groupIds: ["owj0nAfUZGcqsQuYUUW5J"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [132, 189],
          ],
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "branching",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "aMkTJyWkO6LEoTN5g2Lak",
          type: "line",
          x: 636,
          y: 239,
          width: 75,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["_v2IKdPQU46dSl9UlRJ9x"],
          frameId: null,
          index: "aV",
          roundness: null,
          seed: 579547870,
          version: 65,
          versionNonce: 1105878338,
          isDeleted: false,
          boundElements: null,
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [75, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "HW8p3s6Ey8pmdEblyP9OY",
          type: "line",
          x: 637.5,
          y: 375,
          width: 75,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["_v2IKdPQU46dSl9UlRJ9x"],
          frameId: null,
          index: "aW",
          roundness: null,
          seed: 1162985026,
          version: 110,
          versionNonce: 1852215262,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [75, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "89boFFkVhmbJcRKOI_S8l",
          type: "line",
          x: 712,
          y: 239,
          width: 0,
          height: 134,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["_v2IKdPQU46dSl9UlRJ9x"],
          frameId: null,
          index: "aX",
          roundness: null,
          seed: 1978023454,
          version: 101,
          versionNonce: 2096194818,
          isDeleted: false,
          boundElements: null,
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [0, 134],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "lightning-arrester",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "7-Xme6cJGgMgghE7EWJsH",
          type: "line",
          x: 389.5,
          y: 247.75,
          width: 0,
          height: 92,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["xQV4VrU27A6-65TEgFd7_"],
          frameId: null,
          index: "ad",
          roundness: null,
          seed: 2081939230,
          version: 71,
          versionNonce: 2087890014,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [0, 92],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "XgpcgJ4OXitPBzrE6rZu4",
          type: "line",
          x: 441.5,
          y: 342.75,
          width: 102,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["xQV4VrU27A6-65TEgFd7_"],
          frameId: null,
          index: "ae",
          roundness: null,
          seed: 1380600670,
          version: 231,
          versionNonce: 983781506,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-102, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "wKGrwf0YNTxp3kH8CLIa5",
          type: "line",
          x: 429.5,
          y: 356.75,
          width: 75,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["xQV4VrU27A6-65TEgFd7_"],
          frameId: null,
          index: "af",
          roundness: null,
          seed: 1206202270,
          version: 301,
          versionNonce: 811167902,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-75, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "3QIm2c9AelQsQGPOyNrUV",
          type: "line",
          x: 419,
          y: 371.75,
          width: 53,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["xQV4VrU27A6-65TEgFd7_"],
          frameId: null,
          index: "ag",
          roundness: null,
          seed: 1226410974,
          version: 356,
          versionNonce: 816443458,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-53, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "4E4GOyRSsIpid65HV9GCp",
          type: "line",
          x: 408,
          y: 385.25,
          width: 30,
          height: 0,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["xQV4VrU27A6-65TEgFd7_"],
          frameId: null,
          index: "ah",
          roundness: null,
          seed: 335044638,
          version: 430,
          versionNonce: 2069736670,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-30, 0],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "sktm-cable",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "RBLhBnZz_MkxAvbx1pJya",
          type: "line",
          x: 357,
          y: 204,
          width: 197,
          height: 1,
          angle: 0,
          strokeColor: "#e03131",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: [],
          frameId: null,
          index: "ai",
          roundness: null,
          seed: 1365511746,
          version: 43,
          versionNonce: 44957314,
          isDeleted: false,
          boundElements: null,
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [197, -1],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "sutm-cable",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "ZT-bodYk98YnmoCmXeGCe",
          type: "line",
          x: 358.5,
          y: 262.5,
          width: 197,
          height: 1,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: [],
          frameId: null,
          index: "ak",
          roundness: null,
          seed: 1666550942,
          version: 73,
          versionNonce: 1015989506,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [197, -1],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "tr-cable",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "bDh3BcQXRNKcgs-aj9e55",
          type: "line",
          x: 357.5,
          y: 322.5,
          width: 197,
          height: 1,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 2,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: [],
          frameId: null,
          index: "al",
          roundness: null,
          seed: 1480518786,
          version: 91,
          versionNonce: 988385090,
          isDeleted: false,
          boundElements: [],
          updated: Date.now(),
          link: null,
          locked: false,
          points: [
            [0, 0],
            [197, -1],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
    {
      id: "panel",
      status: "published",
      created: Date.now(),
      elements: [
        {
          id: "KX7BqZFOVUtrbrnBj36EX",
          type: "rectangle",
          x: 405,
          y: 126,
          width: 211.99999999999997,
          height: 267,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "am8",
          roundness: null,
          seed: 1064471390,
          version: 115,
          versionNonce: 1968606366,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "Exq_hcU68E72cPjf7C9QW",
          type: "rectangle",
          x: 432,
          y: 153,
          width: 161,
          height: 211,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "amG",
          roundness: null,
          seed: 1526064286,
          version: 62,
          versionNonce: 446469186,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,

        {
          id: "Ja_dQ8dSd-qWE1okYktDF",
          type: "line",
          x: 514,
          y: 173,
          width: 46,
          height: 71,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "amV",
          roundness: null,
          seed: 1300162846,
          version: 47,
          versionNonce: 1515669726,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-46, 71],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 203,
          versionNonce: 276200734,
          index: "aml",
          isDeleted: false,
          id: "VXCviZHYbMI5dlX8lahBf",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 469.3355359569423,
          y: 244,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 88.6644640430577,
          height: 1,
          seed: 1879569090,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: 1723979779756,
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [88.6644640430577, -1],
          ],
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 146,
          versionNonce: 272940034,
          index: "amd",
          isDeleted: false,
          id: "O821GzlW1c0j1Ude6_k30",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 515,
          y: 174.5,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 44,
          height: 68.1315712344462,
          seed: 473261250,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: 1723979779756,
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [44, 68.1315712344462],
          ],
        } as NonDeleted<ExcalidrawElement>,
        {
          id: "-jJbzxObwPG1pG5AUT1VS",
          type: "line",
          x: 516.6644640430577,
          y: 194.46710719138844,
          width: 10.93421438277693,
          height: 24.598678425834663,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "an",
          roundness: null,
          seed: 1976968222,
          version: 38,
          versionNonce: 907144130,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
          points: [
            [0, 0],
            [-10.93421438277693, 24.598678425834663],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,

        {
          type: "line",
          version: 54,
          versionNonce: 1562716510,
          index: "anG",
          isDeleted: false,
          id: "lbmUB53YvgJnp7kkTZYqc",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 520.5328928086116,
          y: 214.5657856172231,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 14.66446404305782,
          height: 21.9342143827769,
          seed: 1788479618,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          roundness: null,
          boundElements: [],
          updated: 1723979779756,
          link: null,
          locked: false,
          startBinding: null,
          endBinding: null,
          lastCommittedPoint: null,
          startArrowhead: null,
          endArrowhead: null,
          points: [
            [0, 0],
            [-14.66446404305782, 21.9342143827769],
          ],
        } as NonDeleted<ExcalidrawElement>,
        {
          id: "WVMe_hOqVdK3jK3da37cL",
          type: "line",
          x: 506.49375425097605,
          y: 219.60456205305562,
          width: 14.39728533128914,
          height: 6.830213900090769,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "anV",
          roundness: null,
          seed: 1554621058,
          version: 50,
          versionNonce: 1378034562,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
          points: [
            [0, 0],
            [14.39728533128914, -6.830213900090769],
          ],
          lastCommittedPoint: null,
          startBinding: null,
          endBinding: null,
          startArrowhead: null,
          endArrowhead: null,
        } as NonDeleted<ExcalidrawElement>,
        {
          id: "FkxO1QEPCgZIYcPMrzWHS",
          type: "rectangle",
          x: 467.5224554938913,
          y: 260.7816336660081,
          width: 90.05888465535156,
          height: 9.059177746396358,
          angle: 0,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          index: "ao",
          roundness: {
            type: 3,
          },
          seed: 2016625090,
          version: 98,
          versionNonce: 800345502,
          isDeleted: false,
          boundElements: null,
          updated: 1723979779756,
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,
        {
          type: "rectangle",
          version: 132,
          versionNonce: 246899522,
          index: "aoV",
          isDeleted: false,
          id: "rSm_jdO4_oTpqPeUqVUlp",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 467.7889018981971,
          y: 288.7585061181142,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 90.05888465535156,
          height: 9.059177746396358,
          seed: 843431746,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          roundness: {
            type: 3,
          },
          boundElements: [],
          updated: 1723979779756,
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,
        {
          type: "rectangle",
          version: 148,
          versionNonce: 1700063710,
          index: "ap",
          isDeleted: false,
          id: "pHWWuUp8YPxq7ogPPWv2w",
          fillStyle: "solid",
          strokeWidth: 4,
          strokeStyle: "solid",
          roughness: 0,
          opacity: 100,
          angle: 0,
          x: 467.78890189819697,
          y: 319.13339620897244,
          strokeColor: "#1e1e1e",
          backgroundColor: "transparent",
          width: 90.05888465535156,
          height: 9.059177746396358,
          seed: 96728670,
          groupIds: ["ZWyDL0Z6l5d8nlvN5umoB"],
          frameId: null,
          roundness: {
            type: 3,
          },
          boundElements: [],
          updated: 1723979779756,
          link: null,
          locked: false,
        } as NonDeleted<ExcalidrawElement>,
      ],
    },
  ];

  return (
    <section
      id="drawing"
      className="max-w-screen relative h-screen max-h-screen overflow-hidden"
    >
      <div style={{ height: "100%", width: "100%" }}>
        {project && (
          <Excalidraw
            excalidrawAPI={(api) => setExcalidrawAPI(api)}
            initialData={{
              appState: {
                currentItemRoughness: 0,
                currentItemFontFamily: 2,
                ...drawingData.appState,
                collaborators: [],
              },
              elements: drawingData.elements,
              libraryItems: initialLibraryItems,
            }}
          >
            <MainMenu>
              <MainMenu.DefaultItems.SaveAsImage />
              <MainMenu.DefaultItems.SaveToActiveFile />
              <MainMenu.ItemCustom
                onClick={handleSave}
                className="my-0 flex items-center gap-2 rounded-md py-0 hover:bg-primary/10"
              >
                <Save className="my-2 size-4" strokeWidth={1.5} />
                Save Project
              </MainMenu.ItemCustom>
              <MainMenu.DefaultItems.ClearCanvas />
              <MainMenu.DefaultItems.ToggleTheme />
              <MainMenu.DefaultItems.ChangeCanvasBackground />
            </MainMenu>
          </Excalidraw>
        )}
      </div>
      <MaterialOverview />
    </section>
  );
}
